sudo: false
distro: trusty

language: python

python:
  - "3.5"
  - "3.6"


install:
  - python3 -m pip install codecov>=2.0.9
  - python3 -m pip install .

script:
  - python3 setup.py test

after_success:
  - codecov
