version: '3'

services:
  _project_-cpython:
    build:
      context: .
      args:
        - PYTHON_IMAGE=${CPYTHON_IMAGE_NAME}
        - PYTHON_IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: _dockerhub_login_/_project_-cpython:_version_
    volumes:
      - ./_project_/:/opt/_project_/_project_/
      - ./tests/:/opt/_project_/tests/
      - ./README.md:/opt/_project_/README.md
      - ./requirements.txt:/opt/_project_/requirements.txt
      - ./requirements-tests.txt:/opt/_project_/requirements-tests.txt
      - ./setup.py:/opt/_project_/setup.py
      - ./pytest.ini:/opt/_project_/pytest.ini
    entrypoint: pytest
