environment:
  GITHUB_ACCESS_TOKEN:
    secure: zmG+7cNvgb5lefPfg6O8472s064F6mPIaatzrgzf7Wjns9Vm34Pk5snWG6CiFVzY
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip wheel setuptools"
  - "%PYTHON%\\python.exe -m pip install --upgrade codecov"

build: false

test_script:
  - "%PYTHON%\\python.exe setup.py test"

on_success:
  - "%PYTHON%\\python.exe -m codecov -f coverage.xml -X gcov"
