version: '3'

services:
  monty:
    build:
      context: .
      args:
        - PYTHON3_VERSION=${PYTHON3_VERSION}
    image: lycantropos/monty:0.0.1-alpha
    volumes:
      - ./template:/opt/monty/template
      - ./scripts:/opt/monty/scripts
      - ./tests:/opt/monty/tests
      - ./README.md:/opt/monty/README.md
      - ./setup.py:/opt/monty/setup.py
      - ./setup.cfg:/opt/monty/setup.cfg
    entrypoint: python3
    command: setup.py test
